<a href="https://colab.research.google.com/github/STARSTEAM-X/LAP_Python/blob/main/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 66015xxx ชื่อ :

Exercise 5.1 ให้เขียน function ชื่อ day_of_year(day, month ,year) โดยมีการคืนค่า คือ day_of_years เป็นวันที่ลำดับที่เท่าใดของปีคริสตศักราช year
ปีที่เป็น Leap Year เดือนกุมภาพันธ์จะมี 29 วัน
ให้สร้างฟังก์ชัน is_leap เพื่อตรวจสอบ leap year แยกออกมา และให้ฟังก์ชัน day_of_year เรียกใช้ is_leap อีกที


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
  pass

def day_of_year(day, month, year):
  pass

# Testcases
print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 181
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

In [1]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
    if (year % 400 == 0) and (year % 100 == 0):
        return True
    elif (year % 4 ==0) and (year % 100 != 0):
        return True

    else:
        return False

def day_of_year(day, month, year):

    if(leap_year(year)):
        days_in_month[1] = 29
    else:
        days_in_month[1] = 28

    day_totle = 0
    day_remove = day

    for i in range(month):
        if(day_remove != 0 and i+1 == month):
            day_totle += day_remove
            day_remove = 0
        else:
            day_totle += days_in_month[i]
    return day_totle

print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 181
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365


Normal year (2023):
1 Jan 2023: 1
1 Feb 2023: 32
1 Mar 2023: 60
31 Dec 2023: 365

Leap year (2024):
1 Jan 2024: 1
29 Feb 2024: 60
1 Mar 2024: 61
31 Dec 2024: 366

Century year, not a leap year (1900):
1 Mar 1900: 60

Century year, leap year (2000):
1 Mar 2000: 61

Mid-year dates:
15 Jun 2023: 166
15 Jun 2024: 167

Last day of each quarter:
31 Mar 2023: 90
30 Jun 2023: 181
30 Sep 2023: 273
31 Dec 2023: 365


Exercise 5.2 ให้เขียนฟังก์ชัน เพิ่มเติมเป็น date_diff
รับข้อมูลในรูปแบบ “dd-mm-yyyy” เช่น date_diff(“1-1-2018”, “1-1-2020”) จะได้ 731 วัน date_diff(“25-12-1999”, “9-3-2000”) จะได้ 76 วัน
ให้เขียนฟังก์ชัน day_in_year โดยจะส่งค่าจำนวนวันของปี (365 หรือ 366) โดยรับข้อมูลเป็น ปี
ส่งคืนข้อมูลเป็นจำนวนวันตั้งแต่วันที่แรก จนถึงวันที่สอง โดยรวมทั้ง 2 วันนั้นเข้าไปด้วย
ให้สมมติว่าวันแรก จะต้องมาก่อนวันที่สองเสมอ ดังนั้นไม่ต้องตรวจสอบ


In [ ]:
def is_leap(year):
    pass

def day_of_year(day, month, year):
    pass

def day_in_year(year):
    return 366 if is_leap(year) else 365

def date_diff(date1, date2):
    pass

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)


In [2]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
    if (year % 400 == 0) and (year % 100 == 0):
        return True
    elif (year % 4 ==0) and (year % 100 != 0):
        return True

    else:
        return False

def day_of_year(day, month, year):

    if(leap_year(year)):
        days_in_month[1] = 29
    else:
        days_in_month[1] = 28

    day_totle = 0
    day_remove = day

    for i in range(month):
        if(day_remove != 0 and i+1 == month):
            day_totle += day_remove
            day_remove = 0
        else:
            day_totle += days_in_month[i]
    return day_totle

def day_in_year(year):
    return 366 if leap_year(year) else 365

def date_diff(date1, date2):
    d1,m1,y1 = date1.split("-")
    d2,m2,y2 = date2.split("-")

    d1 = int(d1)
    d2 = int(d2)
    m1 = int(m1)
    m2 = int(m2)
    y1 = int(y1)
    y2 = int(y2)

    len_of_year = y2-y1
    ans = 0
    if(len_of_year ==0):
        # print(day_of_year(d1,m1,y1),day_of_year(d2,m2,y2))
        ans -= day_of_year(d1,m1,y1)
        ans += day_of_year(d2,m2,y2)
    else:
        for i in range(0,len_of_year):
            year = y1 + i
            # print("X :",day_in_year(year))
            ans += day_in_year(year)
            if(d1 > 1 or m1 > 1 ):
                # print("X :",day_of_year(d1,m1,y1))
                ans -= day_of_year(d1,m1,y1)
            if(d2 > 1 or m2 > 1 ):
                # print("X :",day_of_year(d2,m2,y2))
                ans += day_of_year(d2,m2,y2)
    return ans+1

print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

731
76
367
366
366
365


Exercise 5.3 จากโปรแกรม 5.2 ให้เขียนฟังก์ชัน date_diff  เพิ่มเติม โดยให้มีการตรวจสอบ
วันที่ต้องเป็นวันที่ถูกต้องของเดือนนั้นๆ
เดือนต้องอยู่ระหว่าง 1-12
เดือนกุมภาพันธ์ของปีที่มี Leap Year เท่านั้นที่จะมี 29 วันได้
หากข้อมูล Input ผิดพลาด ให้ Return -1


In [ ]:
def is_leap(year):
    pass

def day_of_year(day, month, year):
    pass

def day_in_year(year):
    return 366 if is_leap(year) else 365

def date_diff(date1, date2):
    pass

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

# ทดสอบกรณีข้อมูลไม่ถูกต้อง
print(date_diff("31-4-2023", "1-5-2023"))  # ควรได้ -1 (เดือนเมษายนมี 30 วัน)
print(date_diff("29-2-2023", "1-3-2023"))  # ควรได้ -1 (ปี 2023 ไม่ใช่ leap year)
print(date_diff("1-13-2023", "1-1-2024"))  # ควรได้ -1 (เดือนไม่ถูกต้อง)
print(date_diff("abc", "1-1-2024"))  # ควรได้ -1 (รูปแบบวันที่ไม่ถูกต้อง)

In [3]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
    if (year % 400 == 0) and (year % 100 == 0): #ปีที่หารด้วย 400 ลงตัว แต่ในทุกๆ 400 ปี จะหารด้วย 100 ลงตัว
        return True
    elif (year % 4 ==0) and (year % 100 != 0): # หาร 4 ลงตัว และ หาร 100 ไม่ลงตัว
        return True
    else:
        return False

def day_of_year(day, month, year):
    if(leap_year(year)):
        days_in_month[1] = 29
    else:
        days_in_month[1] = 28

    day_totle = 0
    day_temp = day

    for i in range(month):
        if(day_temp != 0 and i+1 == month):
            day_totle += day_temp
            day_temp = 0
        else:
            day_totle += days_in_month[i]
    return day_totle

def day_in_year(year):
    return 366 if leap_year(year) else 365

def date_diff(date1, date2):
    try:
        d1,m1,y1 = date1.split("-")
        d2,m2,y2 = date2.split("-")
        d1 = int(d1)
        d2 = int(d2)
        m1 = int(m1)
        m2 = int(m2)
        y1 = int(y1)
        y2 = int(y2)
    except:
        return -1

    if (m1 < 1 or m1 > 12) or (m2 < 1 or m2 > 12): # เดือน น้อยกว่า 1 หรือ มากกว่า 12
        return -1
    elif(d1 > days_in_month[m1-1]): #เช็ควันจะต้องมีค่าไม่มากกว่าวันสูงสุดในเดือน ของ date1
        if(not (leap_year(y1) and d1 == 29)): #เช็คในเดือนกุมภาพันธ์ ถ้าไม่ใช่ leap year ห้ามเกิน 28 day
            return -1
    elif(d2 > days_in_month[m2-1]): #เช็ควันจะต้องมีค่าไม่มากกว่าวันสูงสุดในเดือน ของ date2
        if(not (leap_year(y2) and d2 == 29)): #เช็คในเดือนกุมภาพันธ์ ถ้าไม่ใช่ leap year ห้ามเกิน 28 day
            return -1

    len_of_year = y2-y1
    ans = 0
    if(len_of_year ==0):
        ans -= day_of_year(d1,m1,y1)
        ans += day_of_year(d2,m2,y2)
    else:
        for i in range(0,len_of_year):
            year = y1 + i
            ans += day_in_year(year) #บวกวันตามปี
            if(d1 > 1 or m1 > 1 ):
                ans -= day_of_year(d1,m1,y1) #ลบวันที่เกินเข้ามา
            if(d2 > 1 or m2 > 1 ):
                ans += day_of_year(d2,m2,y2) #บวกวันที่เลื่อนออกไป
    return ans+1

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 366 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

# ทดสอบกรณีข้อมูลไม่ถูกต้อง
print(date_diff("31-4-2023", "1-5-2023"))  # ควรได้ -1 (เดือนเมษายนมี 30 วัน)
print(date_diff("29-2-2023", "1-3-2023"))  # ควรได้ -1 (ปี 2023 ไม่ใช่ leap year)
print(date_diff("1-13-2023", "1-1-2024"))  # ควรได้ -1 (เดือนไม่ถูกต้อง)
print(date_diff("abc", "1-1-2024"))  # ควรได้ -1 (รูปแบบวันที่ไม่ถูกต้อง)

731
76
367
366
366
365
-1
-1
-1
-1


1.	ปลาหมอคางดำเพศเมีย 1 ตัว เมื่ออายุครบ 2 เดือน จะสามารถสืบพันธ์ได้ โดยระยะเวลาตั้งท้องจนถึง
วางไข่ของตัวเมียจะใช้เวลา 21 วัน และฟักในปากเพศผู้อีก 7 วัน (สามารถรวมเป็น 1 เดือนได้) โดยออกไข่ครั้งละ 300 ฟอง กำหนดให้ไข่ฟักเป็นเพศผู้และเพศเมียอย่างละครึ่ง และเมื่อวางไข่แล้วจะสามารถสืบพันธ์ต่อได้ทันที กำหนดให้ปลามีอายุ 5 ปี และปลาทั้งหมดจะตาย p% ทุก 1 เดือน จงหาว่าปลาหมอคางดำหลุดจากฟาร์ม n ตัวเป็นเพศผู้และเพศเมียอย่างละครึ่ง จงเขียนโปรแกรมรับค่า n และ p ให้แสดงผลจำนวนปลาทุก 3 เดือน เป็นเวลา 10 ปี ให้เขียนเป็นฟังก์ชัน ชื่อ simulate_fish_population()


In [ ]:
import math

def simulate_fish_population(n, p, months=3):
  pass

# Run simulation
n = 2  # Initial number of fish
p = 10  # Monthly mortality rate

# simulate_fish_population(n, p)

# ถ้าเริ่มต้นด้วยปลา 2 ตัว ตายเดือนละ 10%
# เดือนที่ 1 ไข่ 300 ไบ
# เดือนที่ 2 ไข่ 300 ใบ + ลูกปลา 270 ตัว
# เดือนที่ 3 ไข่ 300 ใบ + ลูกปลา 270 ตัว + ปลาโตเต็มวัย 243 ตัว + 2 = 515 ตัว


In [16]:
import math

def simulate_fish_population(num, percen):
    data_fish = {
        "male" : {
            "count": [math.floor(num/2)],
            "age" : [0]
        },
        "female":{
            "count": [math.floor(num/2)],
            "age" : [0]
        }
    }

    def total_fish():
        return sum(data_fish["male"]["count"]) + sum(data_fish["female"]["count"])

    def total_male_fish():
        return sum(data_fish["male"]["count"])

    def total_female_fish():
        return sum(data_fish["female"]["count"])

    def age_fish():
        for i in range(len(data_fish["male"]["age"])):
            data_fish["male"]["age"][i] += 1
            data_fish["female"]["age"][i] += 1

    def remove_old_fish():
        for i in range(len(data_fish["male"]["age"]) - 1, -1, -1):
            if data_fish["male"]["age"][i] >= 60:
                data_fish["male"]["count"].pop(i)
                data_fish["male"]["age"].pop(i)
            if data_fish["female"]["age"][i] >= 60:
                data_fish["female"]["count"].pop(i)
                data_fish["female"]["age"].pop(i)

    def new_gen_fish(egg):
        new_males = egg // 2
        new_females = egg // 2
        data_fish["male"]["count"].append(new_males)
        data_fish["male"]["age"].append(0)
        data_fish["female"]["count"].append(new_females)
        data_fish["female"]["age"].append(0)

    year_10_to_month = 120
    egg_per_female = 300

    for month in range(1, year_10_to_month + 1):
        remove_old_fish()

        for i in range(len(data_fish["female"]["count"])):
            if data_fish["female"]["age"][i] >= 2:
                eggs = egg_per_female * data_fish["female"]["count"][i]
                new_gen_fish(eggs)

        # Loss p%
        for i in range(len(data_fish["male"]["count"])):
            data_fish["male"]["count"][i] -= math.floor(data_fish["male"]["count"][i] * percen / 100)
            data_fish["female"]["count"][i] -= math.floor(data_fish["female"]["count"][i] * percen / 100)

        if month % 3 == 0:
            male = total_male_fish()
            female = total_female_fish()
            total = total_fish()
            print(f"Month: {month} || Total: {total}, Male: {male}, Female: {female},")

        age_fish()

n = 2
p = 10
simulate_fish_population(n, p) # Code Run ช้ามาก

Month: 3 || Total: 272, Male: 136, Female: 136,
Month: 6 || Total: 93220, Male: 46610, Female: 46610,
Month: 9 || Total: 520931314, Male: 260465657, Female: 260465657,
Month: 12 || Total: 338480153032, Male: 169240076516, Female: 169240076516,
Month: 15 || Total: 1045634598251130, Male: 522817299125565, Female: 522817299125565,
Month: 18 || Total: 950885227447288842, Male: 475442613723644421, Female: 475442613723644421,
Month: 21 || Total: 2188095294981877799410, Male: 1094047647490938899705, Female: 1094047647490938899705,
Month: 24 || Total: 2424920245028225157359352, Male: 1212460122514112578679676, Female: 1212460122514112578679676,
Month: 27 || Total: 4721859840094201266202720690, Male: 2360929920047100633101360345, Female: 2360929920047100633101360345,
Month: 30 || Total: 5901817741157233316817310330868, Male: 2950908870578616658408655165434, Female: 2950908870578616658408655165434,


KeyboardInterrupt: 

2.	ให้เขียน function find_mismatch ซึ่งรับ string มา 2 ค่า โดยจะส่งค่ากลับดังนี้
- 0 เมื่อ string ทั้ง 2 ตัว เหมือนกัน โดยไม่สนใจ case
- 1 เมื่อ string 1 จะเหมือน string 2 โดยการลบและ/หรือเพิ่มตัวอักษรเพียง 1 ตัว
- 2 เมื่อ string ไม่เข้าเกณฑ์ 0 หรือ 1


| String  1| 	String2	|ผลลัพธ์|
|----------|----------|------|
|Python|	Java	|2|
|book	 |  boot	|1|
|fan	 |  fun	  |1|
|sin	 | sink	  |1 เพราะเพิ่ม k ใน str2 แล้วจะเหมือนกัน
|Dog	 | dog	  |0
|poke	 | spoke	|1 เพิ่ม s ใน str2 แล้วเหมือนกัน
|poker |	poke	|1 ตัด r ใน str1 ออกแล้วเหมือนกัน






In [6]:
def find_mismatch(str1, str2):
    str1 = str1.lower()
    str2 = str2.lower()

    len1, len2 = len(str1), len(str2)
    len_diff = abs(len1 - len2)

    if len_diff > 1 :
        return 2

    if len1 == len2:
        unmatch_count = 0
        for i in range(len1):
            if str1[i] != str2[i]:
                unmatch_count += 1
                if unmatch_count > 1:
                    return 2
        if unmatch_count == 1:
            return 1
    else:
        if len1 < len2:
            str1, str2 = str2, str1

        for i in range(len(str1) + 1):
            if str1[:i] + str1[i:] == str2:
                return 1

# Test cases
print(find_mismatch("Python", "Java"))  # Output: 2
print(find_mismatch("book", "boot"))    # Output: 1
print(find_mismatch("fan", "fun"))      # Output: 1

2
1
1


3.	จากข้อ 1 ให้เขียนฟังก์ชันชื่อ spelling_correction โดยรับ 2 argument ตัวแรกเป็นประโยค (string) และตัวที่ 2 เป็น list ของคำ (correct_spells) โดยฟังก์ชันนี้มีหน้าที่ตรวจสอบแต่ละ word ใน input string กับคำที่อยู่ใน correct_spells โดยค่าที่คืนกลับมาจะมีดังนี้ (พยายามเรียกใช้ฟังก์ชันในข้อ 1)
-	ถ้าคำที่อยู่ในประโยค ตรงกับคำที่อยู่ใน correct_spells ทุกอย่าง ก็จะ copy ไปที่ output string
-	ถ้าคำที่อยู่ในประโยค ต่างจากคำที่อยู่ใน correct_spells โดยต่างกัน 1 ตัวอักษร โดยการเปลี่ยน การเพิ่ม หรือการลบ 1 ตัวอักษร คำที่อยู่ในประโยคจะถูกเปลี่ยนโดยคำที่อยู่ใน correct_spells และนำไปใส่ output string
-	ถ้าคำที่ไม่พบในเงื่อนไขข้างต้นให้นำคำนั้นไปใส่ output string ได้เลย
-	คำที่ประกอบด้วย 1 หรือ 2 ตัวอักษรจะไม่ตรวจสอบ ให้นำคำนั้นไปใส่ output string ได้เลย
-	ถ้ามี 2 คำใน correct_spells ที่ตรงตามเงื่อนไข ให้ใช้คำแรก
-	ไม่สนใจตัวใหญ่ ตัวเล็ก
-	Input string จะมีได้เพียงอักษรภาษาอังกฤษเท่านั้น
-	ในแต่ละคำจะคั่นด้วย 1 space ถ้ามี space มากกว่านั้นให้ตัดออก และตัด space จากหัวท้ายประโยค

|ประโยค	|correct_spells	|output string |
|-------|---------------|-------------|
|Thes is the Firs cas	|[‘that’,’first’,’case’,’car’]|	thes is the first car|
|programming is fan and easy	|[‘programming’,’this’,’fun’,’easy’,book’]	|programming is fun and easy|
|Thes is vary essy	|[‘this’,’is’,’very’,’easy’]	|this is very easy|
|Wee ipve Pythen	|[‘we’,’live’,’ln’,’Python’]	|we live python|




In [8]:
def find_mismatch(str1, str2):
    str1 = str1.lower()
    str2 = str2.lower()

    len1, len2 = len(str1), len(str2)
    len_diff = abs(len1 - len2)

    if len_diff > 1:
        return 2

    if len1 == len2:
        unmatch_count = 0
        for i in range(len1):
            if str1[i] != str2[i]:
                unmatch_count += 1
                if unmatch_count > 1:
                    return 2
        if unmatch_count == 1:
            return 1
        if unmatch_count == 0:
            return 0
    else:
        if len1 < len2:
            str1, str2 = str2, str1

        for i in range(len(str1) + 1):
            if str1[:i] + str1[i+1:] == str2:
                return 1

    return 2

def spelling_correction(input_string, correct_spells):
    str_input = input_string.split(" ")
    correct_input = eval(correct_spells)

    ans = []
    for string in str_input:
        corrected = string
        for correct in correct_input[::-1]:
            if find_mismatch(string, correct) == 0:
                corrected = string
                break
            elif find_mismatch(string, correct) == 1:
                corrected = correct
                break

        ans.append(corrected)

    return " ".join(ans)

# Test cases
print(spelling_correction("Thes is the Firs cas", "['that','first','case','car']"))
print(spelling_correction("programming is fan and easy", "['programming','this','fun','easy','book']"))
print(spelling_correction("Thes is vary essy", "['this','is','very','easy']"))
print(spelling_correction("Wee ipve Pythen", "['we','live','in','python']"))


Thes is the first car
programming is fun and easy
this is very easy
we ipve python


4. ให้เขียนฟังก์ชัน find_word_horizontal ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามแถวของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
	word='cat'
	find_word_horizontal(crosswords,word)
```

Output
   [2,1]


In [9]:
crosswords=[
    ['s','d','o','g'],
    ['c','u','c','m'],
    ['a','c','a','t'],
    ['t','e','t','k']
]
word='cat'

def find_word_horizontal(crosswords, word):
    ans = ''
    x = []
    for i,row in enumerate(crosswords):
        for j,col in enumerate(crosswords):
            ans += crosswords[i][j]
            x.append(f"{i},{j}")

        if word in ans:
            # print(word,ans)
            len_of_word = len(word)
            for i in range(len(ans)):
                if i < len_of_word and word[i] != ans:
                    ans = ans.replace(ans[i], "", 1)
                    x.pop(i)
                    return x[0]
        ans = ''
        x.clear()
    return None

print(find_word_horizontal(crosswords, word))

2,1


5. ให้เขียนฟังก์ชัน find_word_vertical ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามคอลัมน์ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

ตัวอย่าง
```
	crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
	word='cat'
	find_word_vertical(crosswords,word)
```

Output
   [1,0]


In [10]:
crosswords=[
    ['s','d','o','g'],#[0]
    ['c','u','c','m'],#[1][0] ,[1][2]
    ['a','c','a','t'],#[2][0] ,[2][2]
    ['t','e','t','k'] #[3][0] ,[3][2]
]
word='cat'

def find_word_vertical(crosswords, word):
    ans = ''
    x = []
    for i,row in enumerate(crosswords):
        for j,col in enumerate(crosswords):
            ans += crosswords[j][i]
            x.append(f"{i},{j}")

        if word in ans:
            # print(word,ans)
            len_of_word = len(word)
            for i in range(len(ans)):
                if i < len_of_word and word[i] != ans:
                    ans = ans.replace(ans[i], "", 1)
                    x.pop(i)
                    return x[0]
        ans = ''
        x.clear()
    return None

print(find_word_vertical(crosswords, word))

0,1


6.	ให้เขียนฟังก์ชัน capitalize_word_in_crossword จะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตาม row และ column ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบจะเปลี่ยนเป็นตัวใหญ่และ และส่งคืน list ที่แก้ไขแล้ว แต่ถ้าไม่เจอจะส่ง list เดิมกลับมา ให้ใช้ฟังก์ชันตามข้อ 3 และ 4 ช่วย

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','x','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
```
จะส่งค่ากลับ
```
 [['s','d','o','g'],
  ['C','u','c','m'],
  ['A','x','a','t'],
  ['T','e','t','k']]
```
```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
จะส่งค่ากลับ                   
[['s','d','o','g'],
 ['c','u','c','m'],
 ['a','C','A','T'],
 ['t','e','t','k']]
```




In [11]:
crosswords=[
    ['s','d','o','g'],
    ['c','u','c','m'],
    ['a','c','a','t'],
    ['t','e','t','k']
]
word='cat'

def find_word_horizontal(crosswords, word):
    ans = ''
    x = []
    for i,row in enumerate(crosswords):
        for j,col in enumerate(crosswords):
            ans += crosswords[i][j]
            x.append(f"{i},{j}")

        if word in ans:
            # print(word,ans)
            len_of_word = len(word)
            for i in range(len(ans)):
                if i < len_of_word and word[i] != ans:
                    ans = ans.replace(ans[i], "", 1)
                    x.pop(i)
                    return x[0]
        ans = ''
        x.clear()
    return False

def find_word_vertical(crosswords, word):
    ans = ''
    x = []
    for i,row in enumerate(crosswords):
        for j,col in enumerate(crosswords):
            ans += crosswords[j][i]
            x.append(f"{i},{j}")

        if word in ans:
            # print(word,ans)
            len_of_word = len(word)
            for i in range(len(ans)):
                if i < len_of_word and word[i] != ans:
                    ans = ans.replace(ans[i], "", 1)
                    x.pop(i)
                    return x[0]
        ans = ''
        x.clear()
    return False

def format_crossword(crosswords):
    formatted_output = "[\n"
    for row in crosswords:
        formatted_output += f"  {row},\n"
    formatted_output += "]"
    return formatted_output

def capitalize_word_in_crossword(crosswords, word):
    horizontal = find_word_horizontal(crosswords, word)
    vertical = find_word_vertical(crosswords, word)
    print(horizontal)
    print(vertical)
    len_of_word = len(word)

    if ( horizontal == False and vertical == False) :
        return format_crossword(crosswords)

    elif ( horizontal == False and vertical == False) :
        i, j = map(int, horizontal.split(","))
        crosswords_horizontal = crosswords
        crosswords_vertical = crosswords
        for k in range(len_of_word):
            crosswords_horizontal[i][j+k] = crosswords_horizontal[i][j+k].upper()
        for k in range(len_of_word):
            crosswords[j+k][i] = crosswords[j+k][i].upper()
        return format_crossword(crosswords_horizontal),format_crossword(crosswords_vertical)



    elif (horizontal != False):
        i, j = map(int, horizontal.split(","))
        for k in range(len_of_word):
            crosswords[i][j+k] = crosswords[i][j+k].upper()
        return format_crossword(crosswords)

    elif (vertical != False):
        i, j = map(int, vertical.split(","))
        for k in range(len_of_word):
            crosswords[j+k][i] = crosswords[j+k][i].upper()
        return format_crossword(crosswords)

print(capitalize_word_in_crossword(crosswords, word))

2,1
0,1
[
  ['s', 'd', 'o', 'g'],
  ['c', 'u', 'c', 'm'],
  ['a', 'C', 'A', 'T'],
  ['t', 'e', 't', 'k'],
]
